# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c442853eab55d2156b59ea96c2d80b0396ff70da62665b28b0b2a9dff3f407167269e940acee022dbc9b93b7c3cfc22ae19b9a0dacd5ac5595e5cea74426861

test:
  secret_key_base: 17ea241c0dd04d16adee4c8c3334937712159f5d00dd1940ba1a5c93405c528c65b0a9e0814e2241fd01c5f598098fdee0551d62f38c2561808ef77897f73542

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
